### ISSUE TITLE
CombatLog System HCF Servers style

### ISSUE THREAD

**Issue by LuckserSky34** [EternalCodeTeam/EternalCombat#118]
This system spawns a villager for determined time when a player logs out during combat. If the villager is killed, the combat logger's inventory get dropped so if you logout in combat you need to reconnect fast to the game before your combat logger is killed

this system also add a combat-log villager when you disconnect close to other players in combat areas, this prevent the players insta disconnect before the combat-tag ends, so you only way to escape if you are close to other players is using teleports commands like /spawn or using the command /logout this command disconnect you in the zone that you are but don't let combat-log villager spawns, but this command have delay of execution so when you use /logout whit players near you starts a timer of certain time to execute the safe logout

this combat-log system are working in all hcf server, so you can try to see how its works, because its hard to explain in messages.

**Comment by CitralFlo** [comment]
I watched some yt videos about it, but I want to make sure.

![image](https://github.com/EternalCodeTeam/EternalCombat/assets/80779749/e6fa1ec7-f683-4927-b085-5cada8298d05)

During fight, if the User logs out, there will be dummy villager with nametag placed at location where the log off.
The villager can be killed by others to drop items from Users eq, it also kills the player, returning them to spawn empty handed.

Does this feature work during cobat log time, like 20 seconds from last hit? Or always if the User logs in other people's base?

We will discuss this feature on next team meeting. Please provide us with more information. You can link specyfic yt vid for better understanding.

**Comment by LuckserSky34** [comment]
When a player in combat log out, the combat-log villager spawn in the exact location of the logout so the player who logout have around 10s or 15s to reconnect, if not killed he will not lose any item, but if i killed by other player in that 15s the inventory of villager will be drop in the floor and when the player log in will appear in death screen or automatically in the spawn

The combat-log villager spawns always when combat-timer is running
or when you disconnect close to an enemy in regions with pvp on for prevent players to disconnect after the combat-timer ends but this need to be compatible with clans or factions plugin to prevent your teams kill you accidentally

**Comment by LuckserSky34** [comment]
I record 2 videos to explain this

This one is the combat-log, when you logout your combat-time still running for example you disconnect having 15 seconds left of combat-time so your combat-log villager will disappear only when the combat-time expire or if your villager get killed
[Video1](https://www.youtube.com/watch?v=cCAqaRtkeKc)

The second one shows what happen when you disconnect close to an enemy without combat-time in pvp region
[Video2](https://www.youtube.com/watch?v=g09OKu9MrvM)

**Comment by vLuckyyy** [comment]
Better in addon for eternalcombat plugin. Like a EternalCombat-HCFAddon
