### ISSUE TITLE
Improve prevent to enter restricted region.

### ISSUE THREAD

**Issue by Superhyro** [EternalCodeTeam/EternalCombat#127]
So the blocked region feature works well.
But when i enderpearl into spawn and don't move, i will just stay in there until i get out of combat.

And since the worldguard enderpearl flag will also affect non combat players, that isn't a solution for me.
I would really like if this got fixed, since this a problem.

**Comment by vLuckyyy** [comment]
@Superhyro This is fixed in the latest version.
