### ISSUE TITLE
Disable flight while in combat

### ISSUE THREAD

**Issue by Joshuaatan** [EternalCodeTeam/EternalCombat#138]
**Is your feature request related to a problem? Please describe.**

Yes, this plugin is pretty awesome, but there’s just one issue, players are able to fly while in combat or be in flight and combat players

**Describe the solution you'd like**
add a way to disable flight just like elytra 

**Describe alternatives you've considered**
Nil
**Additional context**
Nil

**Comment by igoyek** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Yes, this plugin is pretty awesome, but there’s just one issue, players are able to fly while in combat or be in flight and combat players
> 
> **Describe the solution you'd like**
> add a way to disable flight just like elytra 
> 
> **Describe alternatives you've considered**
> Nil
> **Additional context**
> Nil

Elytra flight blocking is already implemented. A total flight block will be introduced soon (PR is already here) 👍

**Comment by vLuckyyy** [comment]
I'll do a release in the morning.
