### ISSUE TITLE
Restrict to region with world border

### ISSUE THREAD

**Issue by NotAlexNoyle** [EternalCodeTeam/EternalCombat#52]
While in combat on my server, players can run from the warzone to safe regions. Using packets, or APIs from other plugins, it is possible to put up an artificial world border from the perspective of an individual player. I propose using this functionality to restrict players in combat to a particular region. Some other plugins accomplish this by rubber-banding the user when they try to leave the region, I think a world border would be a much nicer solution.

**Comment by Osnixer** [comment]
We added spawn-line feature in #79
