### ISSUE TITLE
Add a bossbar implementation to show the time left in the fight.

### ISSUE THREAD

**Issue by latajacamrufka** [EternalCodeTeam/EternalCombat#86]
It's worth considering the addition of a boss bar implementation that would display the time remaining until the battle starts. It would be nice if the implementation also offered the ability to change the color and style of the boss bar. Additionally, the implementation should dynamically adjust the progress of the boss bar depending on how many seconds are left until the end.

**Comment by NotAlexNoyle** [comment]
While the bossbar is displaying the time left in the fight, I would suggest an option to make the action bar display the number of people you are in combat with (or vise-versa).
